name: Dash Websocket CI for PRs

on:
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-22.04
    env:
      ZMQ_URL: ${{ secrets.ZMQURL }}
      PORT: ${{ secrets.PORT }}
      BIND_ADDRESS: ${{ secrets.BINDADDRESS }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test